title: "Math Notes"
description: "Notes on function theory, operator theory, and related mathematics"
url: "https://jamesftian.github.io"
baseurl: "/math"

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

permalink: /:year/:month/:day/:title/
